### ISSUE TITLE
Fontsize of labels is small. How can i customize it?

### ISSUE THREAD

**Issue by martinsteine** [ghostmaster75/GhostThermostat#3]
Hi, i love the thermostat. However, the font size of the labels (ambience, set, mode, etc.) is quite small. Is there a way to customize it? And another one: most of the thermostats show humidity in the meantime. Is it possible to include the humidity (even a small font would be fine).

**Comment by ghostmaster75** [comment]
you can change the fontsize just add here:
```

    {{'#GhostThermostat' + $id}} .lblDial {
        fill: #dddddd;
    }

```
`font-size statement: 20px;`

change 20px to the size you want-

For now I have not planned nor am I planning to add humidity although I confess that in the initial releases it was there but I didn't like how it was displayed. I thought it made reading a little confusing.
