### ISSUE TITLE
unexpected behaviour when setting setpoint

### ISSUE THREAD

**Issue by jpadie** [ghostmaster75/GhostThermostat#4]
set point does not appear to update until the _next_ ambient temperature reading is provided. 
example is to provide a payload
{ target_temperature: 19}
//nothing happens
{ambient_temperature: 20, target_temperature: 21}
//set point updates to 19
{ambient_temperature:22, target_temperature: 20}
//set point updates to 21

from a brief look the issue stems from render() only being called substantively when the ambient_temperature value is changed. so if the ambient temperature is the first key in the message payload then the other keys are ignored until the next.  

problem is that this means that the ambient temperature must always be provided even when it may not be by the physical or virtual device.  e.g. a matter virtual thermostat commanded to change set point may not also update the ambient temperature.  

suggest that render is called after each message input (not each change in internal variables) that is non-idempotent.

**Comment by ghostmaster75** [comment]
theoretically render is called for each message because if you see in "watch" the variable is set with the value that comes from the message if it exists otherwise it resets it with what is currently valued in the thermostat and then calls render()

**Comment by jpadie** [comment]
Hey Pier

I can see that in the watch function the variables are picked up.  By assigning the values to the properties of the ghostThermostat option you trigger the setters that you established in the define blocks.  You should see there that you are calling render() only when the ambient temperature gets set.  All other properties have their render() calls commented out. 

to allow for setting the options on the fly as well I added a new definition as follow:

        ```
Object.defineProperty(this, 'tempState', {
        	get: function(){
        		return state;
        	},
        	set: function(val){
        		var t = 0;
        		for(var s in state){
        			if(val.hasOwnProperty(s)){
						state[s] = val[s];
						t++;
        			} else if(options.hasOwnProperty(s)){
        				options[s]=val[s];
        				t++;

        			}
        		}
        		if(t>0) render();
        	}
        });
```

and then changed the watch function to 
   ```
scope.$watch('msg', function(data) {
            if(data!== undefined && data.hasOwnProperty("payload"))ghostThermostat.tempState = data.payload;
        });
```

**Comment by jpadie** [comment]
apologies for the format garbling.

**Comment by ghostmaster75** [comment]
Thanks for the tips. If you feel like it, detach a branch and implement the changes. I can't do it now, not even in the immediate future.

**Comment by jpadie** [comment]
Sure, Pier.   I'll look to provide a PR in the next week.  Perhaps tomorrow if the weather is as bad as it looks at the moment...On 20 Oct 2023 20:37, Pier ***@***.***> wrote:
Thanks for the tips. If you feel like it, detach a branch and implement the changes. I can't do it now, not even in the immediate future.
